# Generated by Django 3.2.13 on 2022-12-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro_gallery',
            name='image_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
