# Generated by Django 3.2.13 on 2022-12-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_pro_gallery_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='col_main_name',
            field=models.CharField(default='collection', max_length=255),
        ),
    ]
