# Generated by Django 3.2.13 on 2022-12-16 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_collection_col_main_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='col_main_name',
            field=models.CharField(default=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.all_col'), max_length=255),
        ),
    ]
