# Generated by Django 3.2.13 on 2022-12-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20221217_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='projects',
            field=models.ManyToManyField(to='portfolio.Project'),
        ),
    ]
