# Generated by Django 3.2.13 on 2022-12-17 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_collection_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='projects',
        ),
    ]
