# Generated by Django 3.2.13 on 2022-12-17 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20221217_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='colfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.collection'),
        ),
    ]
