# Generated by Django 3.2.13 on 2022-12-17 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_project_colfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='colfo',
        ),
    ]
